-- liquibase formatted sql

-- changeset black2swan:1
CREATE TABLE if NOT EXISTS rules (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       query TEXT NOT NULL ,
                       arguments TEXT NOT NULL ,
                       negate BOOLEAN NOT NULL
);



